BASE_CONNECT_TO_WINDOW = False

# Serial PORT Setting
BASE_ROBOT_PORT = "/dev/ttyUSB1"
LINEAR_ROBOT_PORT = "/dev/ttyUSB3"
ARM_ROBOT_PORT = ("./arm/katana6M180_G.cfg", "192.168.1.1")
PANTILT_UNIT_PORT = "/dev/ttyUSB0"

BASE_ROBOT = "BASE"
LINEAR_ROBOT = "LINEAR"
ARM_ROBOT = "ARM"
PANTILT_UNIT = "PANTILT"
NETWORK = "NETWORK"
LOCAL_NETWORK = "LOCAL_NETWORK"

ports ={}
ports[BASE_ROBOT] = BASE_ROBOT_PORT
ports[LINEAR_ROBOT] = LINEAR_ROBOT_PORT
ports[ARM_ROBOT] = ARM_ROBOT_PORT
ports[PANTILT_UNIT] = PANTILT_UNIT_PORT

PANTILT_MIN = 200
PANTILT_MAX = 800
PANTILT_MIDDLE = 500

HOKUYO_ID = 2
CAMERA_PAN = 0
CAMERA_TILT = 1
DXL_SPEED = 100

MOBILE_MAX_VOLTAGE = 3

"""MESSGAE LIST"""
CREATE_SERVER = "CREATE_SERVER"
SELECT_ROLE = "SELECT_ROLE"
SERVER_SELECTED = 0
CLIENT_SELECTED = 1
BASE_VELOCITY = "BASE_VELOCITY"
BASE_DISTANCE = "BASE_DISTANCE"

RECEIVE_ENCODER = "RECEIVE_ENCODER"
RESET_ENCODER = "RESET_ENCODER"


""" NETWORK INFO """
SERVER_IP = "192.249.18.35"
SERVER_PORT = 7799
LOCALHOST = "127.0.0.1"
LOCAL_PORT = 7798
WINDOW_SERVER_IP = "192.168.0.2"
#WINDOW_SERVER_IP = "127.0.0.1"
WINDOW_SERVER_PORT = 7797
LINUX_SERVER_IP = "192.168.0.1"
#LINUX_SERVER_IP = "127.0.0.1"
LINUX_SERVER_PORT = 7796



""" Initial_Window Setting """
Initial_Position = (100,100)
Initial_Window_Size = (1200, 600)

ROBOT_PANEL_POS = (10,40)
ROBOT_PANEL_SIZE = (200,200)
ROBOT_SUB_POS = (220, 40)

BASE_ROBOT_POINT_SIZE = 4
""" """
